### PR TITLE
See if we can just add aarch64 and ppc64le

### PR DESCRIPTION
**Pull request by pkgw**
I want to update pango, which means I now need this on the new platforms.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pkgw** [comment]
The new-arch builds fail before actually trying to build this package, with:

```
INFO:conda_build.metadata:Attempting to finalize metadata for fribidi
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/7745eb8d-96ed-4ef7-b665-a5ce63f15f0b' -> '/home/conda/feedstock_root/build_artifacts/linux-ppc64le/repodata.json'
```

@conda-forge/core, anyone know what that's about?

**Comment by jjhelmus** [comment]
> The new-arch builds fail before actually trying to build this package,

I'm seeing the same issue in conda-forge/openssl-feedstock#46

**Comment by pkgw** [comment]
Apparently this got fixed yesterday! I'm actually not quite sure how that happened since I don't know what triggered the new builds, but I'll take it.

**Comment by mbargull** [comment]
We reverted a QEMU update that caused this in the container images: https://github.com/conda-forge/docker-images/pull/109

**Comment by pkgw** [comment]
@mariusvniekerk OK to merge? I think this should supersede #3 as well.

**Comment by pkgw** [comment]
Also pinging @ocefpaf, would unblock some things if we could get this merged.

**Pull request merged**
